apiVersion: apps/v1 
kind: Deployment
metadata:
  name: uberappfe 
spec:
  selector:
    matchLabels:
      app: uberappfe
  replicas: 1  
  template:
    metadata: 
      labels:
        app: uberappfe 
    spec:
      containers:
      - image: 847450032545.dkr.ecr.us-east-1.amazonaws.com/uber-fe:prod
        imagePullPolicy: Always 
        name: uberappfe 
        ports:
          - containerPort: 80