apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler 
metadata:
  name: uberappfe 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: uberappfe
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50