apiVersion: apps/v1 
kind: Deployment
metadata:
  name: uberappbe 
spec:
  selector:
    matchLabels:
      app: uberappbe
  replicas: 1 
  template:
    metadata: 
      labels:
        app: uberappbe 
    spec:
      containers:
      - image: 847450032545.dkr.ecr.us-east-1.amazonaws.com/uber-be:prod
        imagePullPolicy: Always 
        name: uberappbe 
        ports:
          - containerPort: 5000